// Generated by CoffeeScript 1.6.3
(function() {
  var client, io, os, util, zkCfg, zkc, zookeeper, _;

  _ = require('underscore');

  util = require('util');

  os = require('os');

  zookeeper = require('node-zookeeper-client');

  io = require('socket.io').listen(parseInt(process.argv[2] || '8080'));

  zkCfg = process.argv[3] || 'localhost:2181';

  zkc = function() {
    var zk;
    zk = {};
    zk.client = zookeeper.createClient(zkCfg);
    zk.client.once('connected', function() {
      return console.log('Connected to the ZK server.');
    });
    zk.client.connect();
    zk.watch = function(path, socket) {
      var finish, getAndSend, notify;
      finish = function(err, data) {
        return socket.emit('update', {
          path: path,
          value: data.toString()
        });
      };
      notify = function() {
        return zk.client.getData(path, notify, finish);
      };
      getAndSend = function() {
        return zk.client.getData(path, notify, finish);
      };
      return getAndSend();
    };
    return zk;
  };

  client = zkc();

  io.sockets.on('connection', function(socket) {
    console.log('client connected');
    socket.on('watch', function(data) {
      console.log('client subscribe', arguments);
      return client.watch(data.path, socket);
    });
    return socket.on('disconnect', function(socket) {
      return console.log('client disconnected', arguments);
    });
  });

}).call(this);
